import{a as w,S as b,i as p}from"./assets/vendor-mdVVRe9K.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const m="46333898-2c3ef88233fdb340cf3d447ca",E="https://pixabay.com/api/",g=15;async function h(s,r=1){const o=new URLSearchParams({key:m,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:g}),a=`${E}?key=${m}&${o}`,{data:{articles:e,totalResults:t,status:n,message:f=""}}=await w.get(a);if(n!=="ok")throw loader.classList.toggle("loader"),new Error(f);if(e.length===0)throw loader.classList.toggle("loader"),new Error("No photos found");return{articles:e,totalResults:t}}const u=document.querySelector(".gallery"),P=new b(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.7}),y=s=>{const r=s.map(({webformatURL:o,largeImageURL:a,tags:e,likes:t,views:n,comments:f,downloads:v})=>`<li class="gallery-item">
      <a href="${a}" class="gallery-link"><img src="${o}" alt="${e}" class="gallery-img"></a>
      <div class="info-wrapper">
        <p class="info-item">likes<span>${t}</span></p>
        <p class="info-item">views<span>${n}</span></p>
        <p class="info-item">comments<span>${f}</span></p>
        <p class="info-item">downloads<span>${v}</span></p>
      </div>
    </li>`).join("");u.insertAdjacentHTML("beforeend",r),P.refresh(),u.addEventListener("click",o=>o.preventDefault())},S=document.querySelector(".js-search-form"),l=document.querySelector(".js-btn-load-more"),i=document.querySelector(".loader-js");S.addEventListener("submit",$);l.addEventListener("click",q);let c=1,d=null,L=0;async function $(s){s.preventDefault(),u.innerHTML="",c=1;const r=s.currentTarget;if(d=r.elements.query.value,d!==""){l.classList.add("is-hidden"),i.classList.add("loader"),console.log(i);try{const{articles:o,totalResults:a}=await h(d,c);L=Math.ceil(a/g),i.classList.remove("loader"),y(o),l.classList.remove("is-hidden")}catch(o){l.classList.add("is-hidden"),i.classList.remove("loader"),p.error({position:"topLeft",message:o.message,iconUrl:errorIcon})}finally{r.reset()}}}async function q(){c+=1;try{l.classList.add("is-hidden"),i.classList.add("loader");const{articles:s}=await h(d,c);if(y(s),O(),c>=L){p.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topLeft"});return}l.classList.remove("is-hidden")}catch(s){console.log(s)}finally{i.classList.remove("loader")}}function O(){const r=u.lastElementChild.getBoundingClientRect().height;window.scrollBy({top:r*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
